#ifndef _YANJUN_YLIMITS_H_
#define _YANJUN_YLIMITS_H_

#define YYTEXT_MAX_LENGTH 256

#define SYMBOL_BASE 1
#define SYMBOL_LAST	0x7f
#define SYMBOL_CNT	(SYMBOL_LAST-SYMBOL_BASE+1)
#define SYMBOL_ALL_CNT	(SYMBOL_LAST+1)

#define TERMEOF		 (SYMBOL_LAST+1)
#define TERMEMPTY	 (SYMBOL_LAST+2)
#define TERMVIRTUAL	 (SYMBOL_LAST+3)

#define TERM_BASE	 (TERMVIRTUAL+1)
#define TERM_MAX_COUNT 128

#define NONTERM_BASE (TERM_BASE+TERM_MAX_COUNT)
#define NONTERM_MAX_COUNT 256

#define NONTERM_STARTSYMBOL (NONTERM_BASE+NONTERM_MAX_COUNT+'y')

#define RULEBODY_MAX_LENGTH 256
#define RULEACTION_MAX_LENGTH	512
#define RULE_MAX_COUNT 256

#define LALR1STATE_MAX_COUNT 1000

#define PARSESTACK_SIZE 256

#define VALTYPE_MAX_COUNT 100
#define VALTYPE_MAX_LENGTH 50

#define TERMNAME_MAX_LENGTH 50

#define TOKEN -1
#define ASSOC_NON 0
#define ASSOC_LEFT 1
#define ASSOC_RIGHT 2

#endif