#ifndef _YANJUN_YTOKEN_H_
#define _YANJUN_YTOKEN_H_
enum YACC_TERM{YACC_PARTION=TERM_BASE,YACC_LITLEFT,YACC_ACTION,
YACC_IDENTIFIER,YACC_STARTRULE,YACC_UNION,YACC_LEFT,YACC_RIGHT,
YACC_NONASSOC,YACC_CHAR,YACC_PREC,YACC_TOKEN,YACC_TYPE};
#endif